name: pre_merge

on:
  # pull_request:
  #   branches:
  #     - master
  #     - dev
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pytest_fast:
    strategy:
      matrix:
        # os: [ ubuntu-24.04 ]
        os: [ macos-15 ]
        # os: [ubuntu-24.04, macos-15]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          python-version: "3.12"
          cache-suffix: ${{ runner.os }}-${{ runner.arch }}-py3.12

      - name: Install System dependencies
        run: |
          # if macos
          if [ "$(uname)" = "Darwin" ]; then
            # because we add "-march=native" in setup.py and there's a compiler arg issue with that on macos arm
            target="$(uname -m)"
            target="arm64"
            export ARCHFLAGS="-arch "
            export CXXFLAGS="-Xclang -target-cpu -Xclang "
            export CFLAGS="-Xclang -target-cpu -Xclang "
            # install brew
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew install gnu-sed portaudio git-lfs libjpeg-turbo pre-commit
            export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
          # if ubuntu
          else
            sudo apt-get update
            sudo apt-get install -y \
              curl \
              g++ \
              portaudio19-dev \
              git-lfs \
              libturbojpeg \
              python3-dev \
              pre-commit
          fi

      - name: Install and run tests
        run: |
          bin/ci-fast