name: quickstart-ci

on:
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quick-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ubuntu system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            g++ \
            portaudio19-dev \
            git-lfs \
            libturbojpeg \
            python3-dev \
            pre-commit

      - name: Cache uv downloads/builds
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-py312-${{ hashFiles('~/.cache/uv/**/*') }}
          restore-keys: |
            uv-${{ runner.os }}-py312-
            uv-${{ runner.os }}-

      - name: Follow Development Install and Test
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          # if uv not here, get it
          curl -LsSf https://astral.sh/uv/install.sh | sh
        
          uv venv
          . .venv/bin/activate

          git clone https://github.com/dimensionalOS/dimos.git
          cd dimos
          git checkout dev

          uv pip install -e '.[base,dev,manipulation,misc,unitree,drone]'
          
          # FIXME:
          pytest dimos/robot/test_all_blueprints_generation.py::test_all_blueprints_is_current
          
          # Run mypy check for multiple Python versions
          uv run mypy --python-version 3.10 dimos
          uv run mypy --python-version 3.12 dimos
          
          
          echo "# "
          echo "# "
          echo "# pytest fast"
          echo "# "
          echo "# "
          bin/pytest-fast | tee pytest-fast.log
          echo "exit code $?"
          # if there's any failure 
          grep -q "FAILED" pytest-fast.log && exit 1
          
        #   echo "# "
        #   echo "# "
        #   echo "# pytest slow"
        #   echo "# "
        #   echo "# "
        #   pytest dimos | tee pytest-fast.log
        #   echo "exit code $?"
        #   # if there's any failure 
        #   grep -q "FAILED" pytest-fast.log && exit 1